---
title: "Visualization"
author: "Jiacheng Wu"
date: "10/9/2021"
output: html_document
---

```{r}
library(tidyverse)
library(ggridges)
```

## Load the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## Scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

Same plot, different approach

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

Save and edit a plot object

```{r}
plot_weather = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()
```

## Advanced scatterplot ... 

Start with the same one and make it fancy

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point() +
  geom_smooth(se = FALSE)
```

What about the `aes` placement

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) +
  geom_smooth()
```

Facet some things!

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp)) + 
  geom_point(alpha = .3) +
  facet_grid(. ~ name) +
  geom_smooth(se = FALSE) 
```


## Use data manipulation as part of this

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax = tmax * (9 / 5) + 32,
    tmin = tmax * (9 / 5) + 32
  ) %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

## Stacking geoms

Which geoms do you want?

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth()
```

Hexagons

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```

